language: objective-c
osx_image: xcode7.3
xcode_workspace: Harekaze.xcworkspace
xcode_scheme: Harekaze
xcode_sdk: iphonesimulator9.3
cache: cocoapods
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - pod repo update --silent
